// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.3
// source: internal/orderpb/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      string                 `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_internal_orderpb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orderpb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_orderpb_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer      string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_internal_orderpb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orderpb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_internal_orderpb_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_internal_orderpb_order_proto protoreflect.FileDescriptor

const file_internal_orderpb_order_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/orderpb/order.proto\x12\aorderpb\"0\n" +
	"\x12CreateOrderRequest\x12\x1a\n" +
	"\bcustomer\x18\x01 \x01(\tR\bcustomer\"j\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2J\n" +
	"\fOrderService\x12:\n" +
	"\vCreateOrder\x12\x1b.orderpb.CreateOrderRequest\x1a\x0e.orderpb.OrderB\x12Z\x10internal/orderpbb\x06proto3"

var (
	file_internal_orderpb_order_proto_rawDescOnce sync.Once
	file_internal_orderpb_order_proto_rawDescData []byte
)

func file_internal_orderpb_order_proto_rawDescGZIP() []byte {
	file_internal_orderpb_order_proto_rawDescOnce.Do(func() {
		file_internal_orderpb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_orderpb_order_proto_rawDesc), len(file_internal_orderpb_order_proto_rawDesc)))
	})
	return file_internal_orderpb_order_proto_rawDescData
}

var file_internal_orderpb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_orderpb_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: orderpb.CreateOrderRequest
	(*Order)(nil),              // 1: orderpb.Order
}
var file_internal_orderpb_order_proto_depIdxs = []int32{
	0, // 0: orderpb.OrderService.CreateOrder:input_type -> orderpb.CreateOrderRequest
	1, // 1: orderpb.OrderService.CreateOrder:output_type -> orderpb.Order
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_orderpb_order_proto_init() }
func file_internal_orderpb_order_proto_init() {
	if File_internal_orderpb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_orderpb_order_proto_rawDesc), len(file_internal_orderpb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_orderpb_order_proto_goTypes,
		DependencyIndexes: file_internal_orderpb_order_proto_depIdxs,
		MessageInfos:      file_internal_orderpb_order_proto_msgTypes,
	}.Build()
	File_internal_orderpb_order_proto = out.File
	file_internal_orderpb_order_proto_goTypes = nil
	file_internal_orderpb_order_proto_depIdxs = nil
}
